services:
  prometheus:
    image: dhi.io/prometheus:3.13
    user: '0:0'
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus:/etc/prometheus

      - prom_data:/prometheus

  loki:
    image: grafana/loki
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yml:ro
      - ./monitoring/loki/rules.yml:/etc/loki/rules.yml:ro

      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yml
    restart: unless-stopped
    ports:
      - '3100:3100'

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager.yml:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - '9093:9093'

  server:
    build:
      context: .
    ports:
      - '3000:3000'

  compass:
    image: omarmohamed04/compass-app:v1.0

    ports:
      - '8000:8000'
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: dhi.io/redis:8-debian-dev
    ports:
      - '6379:6379'

  rabbitmq:
    image: dhi.io/rabbitmq:4-debian-dev
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  prom_data:
  loki-data:
