services:
  prometheus:
    image: dhi.io/prometheus:3.13
    user: '0:0'
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus:/etc/prometheus

      - prom_data:/prometheus

  loki:
    image: grafana/loki
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yml:ro
      - ./monitoring/loki/rules.yml:/etc/loki/rules.yml:ro
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yml
    restart: unless-stopped
    ports:
      - '3100:3100'

  server:
    build:
      context: .
    environment:
      SERVICE_NAME: compass
      LOKI_URL: http://loki:3100
    depends_on:
      - loki
    ports:
      - '3000:3000'
  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager.yml:ro
    command:
      - --config.file=/etc/alertmanager.yml
    ports:
      - '9093:9093'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    privileged: true
    devices:
      - /dev/kmsg

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - '9100:9100'


  compass:
      build:
        context: ./compass/.
      environment:
        COMPASS_PROMETHEUS_URL: http://prometheus:9090
        COMPASS_LOKI_URL: http://loki:3100
        COMPASS_REDIS_URL: redis://redis:6379/0
        COMPASS_RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      ports:
        - '8000:8000'
      depends_on:
        - redis
        - rabbitmq
      develop:
        watch:
          - action: rebuild
            path: ./compass

  redis:
    image: dhi.io/redis:8-debian-dev
    ports:
      - '6379:6379'

  rabbitmq:
    image: dhi.io/rabbitmq:4-debian-dev
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit loopback_users []"
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  prom_data:
  loki-data:
