"""
Generates a markdown incident report from a full pipeline run and
persists it (SQLite for dev, swap DATABASE_URL for Postgres in prod).
This is what makes postmortems fast: the "why" is written down the
moment the decision is made, not reconstructed hours later.
"""
from datetime import datetime
from sqlalchemy import create_engine, Column, String, Integer, DateTime, Text
from sqlalchemy.orm import declarative_base, sessionmaker

from app.models import DeploymentEvent, Layer1Result, Layer2Result, Layer3Result, DecisionResult, IncidentReport
from app.config import settings

Base = declarative_base()
engine = create_engine(settings.database_url, connect_args={"check_same_thread": False})
SessionLocal = sessionmaker(bind=engine)


class IncidentRecord(Base):
    __tablename__ = "incidents"
    id = Column(Integer, primary_key=True, autoincrement=True)
    app_name = Column(String)
    commit_sha = Column(String)
    action = Column(String)
    decided_by_layer = Column(Integer)
    confidence = Column(Integer, nullable=True)
    root_cause = Column(String, nullable=True)
    markdown = Column(Text)
    created_at = Column(DateTime, default=datetime.utcnow)


Base.metadata.create_all(engine)


def build_report(
    deployment: DeploymentEvent,
    layer1: Layer1Result,
    decision: DecisionResult,
    layer2: Layer2Result | None = None,
    layer3: Layer3Result | None = None,
    hotfix: dict | None = None,
) -> IncidentReport:
    md = [
        f"# Incident Report — {deployment.app_name}",
        f"**Generated:** {datetime.utcnow().isoformat()}Z",
        f"**Commit:** `{deployment.commit_sha}` — {deployment.commit_message or 'n/a'}",
        f"**Decision:** `{decision.action}` (decided by Layer {decision.decided_by_layer})",
        f"**Reason:** {decision.reason}",
        "",
        "## Layer 1 — Rule-based Gate",
        f"- Verdict: `{layer1.verdict}`",
        f"- Reason: {layer1.reason}",
        f"- Details: `{layer1.details}`",
    ]

    if layer2:
        md += [
            "",
            "## Layer 2 — Statistical Anomaly Detection",
            f"- Verdict: `{layer2.verdict}`",
            f"- Deviation score: {layer2.deviation_score}",
            f"- Reason: {layer2.reason}",
        ]

    if layer3:
        md += [
            "",
            "## Layer 3 — AI Root Cause Analysis",
            f"- Status: `{layer3.status}`",
            f"- Root cause: {layer3.root_cause}",
            f"- Confidence: {layer3.confidence}%",
            f"- Explanation: {layer3.explanation}",
            f"- Evidence: `{layer3.evidence_summary}`",
        ]

    if hotfix and hotfix.get("attempted"):
        md += ["", "## Hotfix PR"]
        if hotfix.get("opened_pr"):
            md += [
                f"- Opened draft PR: {hotfix.get('pr_url')}",
                f"- Branch: `{hotfix.get('branch')}`",
                f"- Summary: {hotfix.get('summary')}",
                "- **Human review required before merging.**",
            ]
        else:
            md += [f"- Not opened: {hotfix.get('reason')}"]

    md += ["", "---", "*Auto-generated by compass.*"]
    markdown = "\n".join(md)

    return IncidentReport(
        deployment=deployment, layer1=layer1, layer2=layer2, layer3=layer3,
        decision=decision, hotfix=hotfix, markdown=markdown,
    )


def save_report(report: IncidentReport):
    session = SessionLocal()
    try:
        record = IncidentRecord(
            app_name=report.deployment.app_name,
            commit_sha=report.deployment.commit_sha,
            action=report.decision.action,
            decided_by_layer=report.decision.decided_by_layer,
            confidence=report.decision.confidence,
            root_cause=report.layer3.root_cause if report.layer3 else None,
            markdown=report.markdown,
        )
        session.add(record)
        session.commit()
    finally:
        session.close()
